// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	GOOGLE_CLOUD_PROJECT_ID: string;
	GOOGLE_CLOUD_SERVICE_ACCOUNT: string;
	JWT_SECRET: string;
}
