// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	APPWRITE_API_SECRET: string;
	APPWRITE_PROJECT_ID: string;
	APPWRITE_DATABASE_ID: string;
	JWT_SECRET: string;
}
